### ISSUE TITLE
about point features

### ISSUE THREAD

**Issue by xiaolinpan** [dgriffiths3/pointnet2-tensorflow2#2]
hello, every point don't have feature in the modelnet example scripts, can i add the feature for the point in my research? Your implement of pointNet2 is supporting this operation ? Thank you vary much!

**Comment by dgriffiths3** [comment]
When you say feature, do you mean a hand crafted local neighbourhood feature? Or something else?

**Comment by xiaolinpan** [comment]
Thank you for your reply! Every point may be need a some feature for descript it, like RGB. For example, a atom in molecular, it have some feature to descript the property, like element(C, H, O, N, S, P...), aromatic, hydrogen number, etc. My work focus on drug design, and i want to Study protein-ligand interaction using pointNet2, only use point coordinate can't descript the atom in protein and ligand, do you have some suggestion for my Study? or pointNet2 is not satisfied this research?

**Comment by dgriffiths3** [comment]
Okay, I understand. It is possible to add extra features to pointnet++ (RGB, Normals or anything you choose such as C, H, O, N, S) **in addition** to XYZ points. These features are concatenated to the XYZ coordinates before being passed into the MLP at each layer. However, the down sampling at each layer is done spatially on the XYZ coordinates only. 

This means you can only do the down sampling on 3 features. So sure, you could change XYZ for 3 different features, but the new features would have make spatial sense in a Euclidean coordinate system. The whole idea of PointNet++ is local features hold information about features close by. This holds true for XYZ points of an object, but maybe not for your features. 

I don't know anything about your specific use case, but if you do still have some form of XYZ to do the spatial down sampling (or something similarly appropriate) then I can show you how to easily add the extra features to each point.

If not, I would reccommend using [PointNet](https://github.com/dgriffiths3/pointnet2-tensorflow2/blob/master/models/cls_basic_model.py) which can take any number of features (XYZ or otherwise), without any issues.

**Comment by xiaolinpan** [comment]
Thank you very much! I have understood

**Comment by kapsl** [comment]
Hi.
I opened a new issue on this. In the original implementation it seems to be possible to add features?
